site_name: INS PEDRALBES Jordi Cervera
nav:
    - Inici: 'index.md'
    - 'Assignatures':
       - 'M02': 'basededades.md'
       - 'M03': 'programacio.md'
       - 'M05': 'entorndesenvolupament.md'
       - 'M06': 'dwentornclient.md'
       - 'M07': 'dwentornservidor.md'

theme: readthedocs